Add guide
nieltg/rails-blog-app pull request #3
Opened 2020-03-11 04:31 UTC by iamdejan

List of changes:
- Add guide to `README.md` file.
- Update `.gitignore` file.

2020-03-29 03:53 UTC, nieltg commented
Hey, I have a lot of notifications in my GitHub. I just noticed this. I'll review.

2020-03-29 04:01 UTC, nieltg requested changes

2020-03-29 04:01 UTC, nieltg commented on README.md
> +3) Create role `blog` with `superuser` access.
What is this? I think there's no auth yet in this app. 😌

2020-03-29 04:01 UTC, nieltg commented on README.md
> +3) Create role `blog` with `superuser` access.
Oh, maybe you can make it clear by specifying that it should be done on the database. Or just specify **Postgres role.**

2020-03-29 04:01 UTC, nieltg commented on README.md
> +4) Create database `blog_development`.
Will be better if:
```
Create database `blog_development` under `blog` role.
```

2020-03-29 15:17 UTC, iamdejan commented on config/routes.rb
> +  resources :posts, path: '/posts'
Well, the comments are lying, then. See at [L4-L5](https://github.com/nieltg/rails-blog-app/blob/c38877ec10bd77db443022b7f8054146a3493455/app/controllers/posts_controller.rb#L4-L5) and the rest of the file.
Do you prefer to fix the comment / fix the routing?

2020-03-29 15:19 UTC, iamdejan commented on .gitignore
> +/*/**/.idea
> Will `.idea` be placed in another folder other than root project?
No

2020-03-29 17:34 UTC, nieltg commented on config/routes.rb
> +  resources :posts, path: '/posts'
Sorry, it's Rails generated controllers. I even didn't know that it's a comment there.

I prefer to fix or better to remove the comments there. 😂
Why I prefer to remove the comment is because sometimes it can be misleading if you forget to update the comment. Look at [this reference](https://pragtob.wordpress.com/2017/11/14/are-comments-a-code-smell-yes-no-it-depends).

2020-03-29 17:37 UTC, nieltg commented on .gitignore
> +/*/**/.idea
Cool. So it should be `/.idea` then.

2020-03-30 10:09 UTC, nieltg requested changes
Thank you for contributing! There are some changes that should be done before merging this PR.

2020-04-13 08:20 UTC, iamdejan commented
I have applied your reviews, please kindly help to review again.

2020-04-13 10:21 UTC, nieltg approved these changes

2020-04-13 10:22 UTC, merged

2020-04-13 10:23 UTC, nieltg commented
Merged. Thanks! @iamdejan